### ISSUE TITLE
Not able to start pandora in latest version of raspian jessi

### ISSUE THREAD

**Issue by John-F-R** [kimberli/raspi#1]
Not sure if you are still maintaining this project or not, but I am not able to get the start pandora button to work in Raspbian jessie

**Comment by kimberli** [comment]
To be honest, I haven't touched this in years. It's probably an issue with Pianobar--read the README for instructions on how I set it up (which might not work anymore). The Pianobar repo looks like it's still being maintained, so I would try opening an issue there if you're still facing problems!

**Comment by John-F-R** [comment]
it was actually a mistake of my own, I had the configure path wrong in the apache folder. Got it working fine now.
